# RuboCop configuration
# Basic configuration with relaxed rules for development

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

# Disable some strict rules for development
Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false
